safe: true
lsi: false
highlighter: rouge
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-redirect-from
url: https://wp-cli.org
permalink: /blog/:title.html
paginate: 10
paginate_path: /blog/page:num
include:
  - _s
exclude:
  - bin
  - vendor
  - Phakefile.php
  - README.md
navigation:
- text: Commands
  url: https://developer.wordpress.org/cli/commands/
- text: Configuration
  url: https://make.wordpress.org/cli/handbook/config/
- text: Handbook
  url: https://make.wordpress.org/cli/handbook/
- text: Blog
  url: https://make.wordpress.org/cli/
- text: Contributing
  url: https://make.wordpress.org/cli/handbook/contributing/
languages:
- label: English
  iso-alpha2: en
  path: /
- label: Japanese
  iso-alpha2: ja
  path: /ja/
- label: Français
  iso-alpha2: fr
  path: /fr/
- label: Português (Brasil)
  iso-alpha2: br
  path: /br/
- label: Türkçe
  iso-alpha2: tr
  path: /tr/
- label: Deutsch
  iso-alpha2: de
  path: /de/
- label: नेपाली
  iso-alpha2: ne
  path: /ne/
- label: ελληνικά
  iso-alpha2: gr
  path: /gr/
- label: Italiano
  iso-alpha2: it
  path: /it/
- label: Español
  iso-alpha2: es
  path: /es/
- label: română
  iso-alpha2: ro_RO
  path: /ro/
